players:
- category: 測試
  name: 板橋11F-測試用
  ip_port: 192.168.29.247:5000
- category: 光澤
  name: 新莊光澤-2F大廳
  ip_port: 192.168.38.247:5000
- category: 光澤
  name: 新竹光澤-2F大廳
  ip_port: 192.168.34.247:5000
- category: 彤顏
  name: 永和彤顏-2F大廳
  ip_port: 192.168.36.247:5000
- category: 中醫
  name: 新莊京都堂-1F大廳&2F大廳
  ip_port: 192.168.37.247:5000
- category: 彤顏
  name: 林口彤顏-2F大廳
  ip_port: 192.168.21.247:5000
- category: 彤顏
  name: 中壢彤顏醫美-2F大廳
  ip_port: 192.168.3.247:5000
- category: 彤顏
  name: 中壢彤顏醫美-3F大廳
  ip_port: 192.168.3.246:5000
- category: 彤顏
  name: 中壢彤顏健保-1F大廳
  ip_port: 192.168.3.245:5000
- category: 彤顏
  name: 中壢彤顏會館-2F大廳
  ip_port: 192.168.3.244:5000
- name: 忠孝光澤-5F大廳
  ip_port: 192.168.6.247:5000
- name: 忠孝光澤-6F等候區
  ip_port: 192.168.6.248:5000
- name: 台北京都堂-1F大廳&2F大廳
  ip_port: 192.168.26.247:5000
